FROM ubuntu:20.04

USER root

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        autoconf automake autotools-dev curl libmpc-dev libmpfr-dev libgmp-dev \
        gawk build-essential bison flex texinfo gperf libtool patchutils bc \
        zlib1g-dev libexpat-dev pkg-config  libglib2.0-dev libpixman-1-dev libsdl2-dev \
        git tmux python3 python3-pip ninja-build tar

RUN git clone https://github.com/a1393323447/zCore-OS.git && \
    curl https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz --output zig-linux-x86_64-0.11.0.tar.xz && \
    tar xvJf zig-linux-x86_64-0.11.0.tar.xz && \
    mv zig-linux-x86_64-0.11.0 .zig && \
    curl https://download.qemu.org/qemu-7.0.0.tar.xz --output qemu-7.0.0.tar.xz && \
    tar xvJf qemu-7.0.0.tar.xz && \
    cd qemu-7.0.0 && \
    ./configure --target-list=riscv64-softmmu,riscv64-linux-user && \
    make -j4 && \
    make install

ENV PATH $PATH:/.zig
